app:
  name: 'app'
  version: '1.0.0'  

logger:
  log_level: 'debug'
  # rollbar_env: 'go-clean-template'

consul:  
  checkApi: '/healthz'
  # consul心跳间隔, 秒
  interval: 3
  # 心跳超时, 秒
  timeout: 3

postgres:
  pool_max: 2
  url: 'postgresql://dev_user:dev123@dog.ap:5432/app'

action:
  save:
    table: [ 't_app', 't_app_type_rel' ]
  query:
    type: 1
    table: 
      - 
        name: 't_app'
        columns: [ 'id', 'name', 'icon' ]
        key: 'id'
      - 
        name: 't_app_type_rel'
        columns: [ 'type_id' ]
        key: 'app_id'
